//! Linux-native keycodes for CEF key events.

use winit::keyboard::KeyCode;

/// Map a winit physical `KeyCode` to the Linux XKB keycode (evdev scancode + 8) that CEF's Linux OSR
/// key translation expects in `KeyEvent.native_key_code`. Chromium derives the DOM `KeyboardEvent.code`
/// (the physical `"KeyW"` string every registry shortcut and the fly-cam match on) from this via
/// `NativeKeycodeToDomCode`; without it `event.code` is empty and only character-based text entry works.
pub fn native_from_keycode(code: KeyCode) -> i32 {
    match code {
        KeyCode::Escape => 9,
        KeyCode::Digit1 => 10,
        KeyCode::Digit2 => 11,
        KeyCode::Digit3 => 12,
        KeyCode::Digit4 => 13,
        KeyCode::Digit5 => 14,
        KeyCode::Digit6 => 15,
        KeyCode::Digit7 => 16,
        KeyCode::Digit8 => 17,
        KeyCode::Digit9 => 18,
        KeyCode::Digit0 => 19,
        KeyCode::Minus => 20,
        KeyCode::Equal => 21,
        KeyCode::Backspace => 22,
        KeyCode::Tab => 23,
        KeyCode::KeyQ => 24,
        KeyCode::KeyW => 25,
        KeyCode::KeyE => 26,
        KeyCode::KeyR => 27,
        KeyCode::KeyT => 28,
        KeyCode::KeyY => 29,
        KeyCode::KeyU => 30,
        KeyCode::KeyI => 31,
        KeyCode::KeyO => 32,
        KeyCode::KeyP => 33,
        KeyCode::BracketLeft => 34,
        KeyCode::BracketRight => 35,
        KeyCode::Enter => 36,
        KeyCode::ControlLeft => 37,
        KeyCode::KeyA => 38,
        KeyCode::KeyS => 39,
        KeyCode::KeyD => 40,
        KeyCode::KeyF => 41,
        KeyCode::KeyG => 42,
        KeyCode::KeyH => 43,
        KeyCode::KeyJ => 44,
        KeyCode::KeyK => 45,
        KeyCode::KeyL => 46,
        KeyCode::Semicolon => 47,
        KeyCode::Quote => 48,
        KeyCode::Backquote => 49,
        KeyCode::ShiftLeft => 50,
        KeyCode::Backslash => 51,
        KeyCode::KeyZ => 52,
        KeyCode::KeyX => 53,
        KeyCode::KeyC => 54,
        KeyCode::KeyV => 55,
        KeyCode::KeyB => 56,
        KeyCode::KeyN => 57,
        KeyCode::KeyM => 58,
        KeyCode::Comma => 59,
        KeyCode::Period => 60,
        KeyCode::Slash => 61,
        KeyCode::ShiftRight => 62,
        KeyCode::NumpadMultiply => 63,
        KeyCode::AltLeft => 64,
        KeyCode::Space => 65,
        KeyCode::CapsLock => 66,
        KeyCode::F1 => 67,
        KeyCode::F2 => 68,
        KeyCode::F3 => 69,
        KeyCode::F4 => 70,
        KeyCode::F5 => 71,
        KeyCode::F6 => 72,
        KeyCode::F7 => 73,
        KeyCode::F8 => 74,
        KeyCode::F9 => 75,
        KeyCode::F10 => 76,
        KeyCode::NumLock => 77,
        KeyCode::ScrollLock => 78,
        KeyCode::Numpad7 => 79,
        KeyCode::Numpad8 => 80,
        KeyCode::Numpad9 => 81,
        KeyCode::NumpadSubtract => 82,
        KeyCode::Numpad4 => 83,
        KeyCode::Numpad5 => 84,
        KeyCode::Numpad6 => 85,
        KeyCode::NumpadAdd => 86,
        KeyCode::Numpad1 => 87,
        KeyCode::Numpad2 => 88,
        KeyCode::Numpad3 => 89,
        KeyCode::Numpad0 => 90,
        KeyCode::NumpadDecimal => 91,
        KeyCode::F11 => 95,
        KeyCode::F12 => 96,
        KeyCode::NumpadEnter => 104,
        KeyCode::ControlRight => 105,
        KeyCode::NumpadDivide => 106,
        KeyCode::AltRight => 108,
        KeyCode::Home => 110,
        KeyCode::ArrowUp => 111,
        KeyCode::PageUp => 112,
        KeyCode::ArrowLeft => 113,
        KeyCode::ArrowRight => 114,
        KeyCode::End => 115,
        KeyCode::ArrowDown => 116,
        KeyCode::PageDown => 117,
        KeyCode::Insert => 118,
        KeyCode::Delete => 119,
        KeyCode::SuperLeft => 133,
        KeyCode::SuperRight => 134,
        KeyCode::ContextMenu => 135,
        _ => 0,
    }
}
