//! macOS-native keycodes for CEF key events.

use winit::keyboard::KeyCode;

/// Map a winit physical `KeyCode` to the macOS virtual keycode (`kVK_*`, Carbon `Events.h`) that
/// CEF's mac OSR key translation expects in `KeyEvent.native_key_code`. Chromium derives the DOM
/// `KeyboardEvent.code` (the physical `"KeyW"` string every registry shortcut and the fly-cam
/// match on) from this via `NativeKeycodeToDomCode`; without it `event.code` is empty and only
/// character-based text entry works.
pub fn native_from_keycode(code: KeyCode) -> i32 {
    match code {
        KeyCode::KeyA => 0x00,
        KeyCode::KeyS => 0x01,
        KeyCode::KeyD => 0x02,
        KeyCode::KeyF => 0x03,
        KeyCode::KeyH => 0x04,
        KeyCode::KeyG => 0x05,
        KeyCode::KeyZ => 0x06,
        KeyCode::KeyX => 0x07,
        KeyCode::KeyC => 0x08,
        KeyCode::KeyV => 0x09,
        KeyCode::KeyB => 0x0B,
        KeyCode::KeyQ => 0x0C,
        KeyCode::KeyW => 0x0D,
        KeyCode::KeyE => 0x0E,
        KeyCode::KeyR => 0x0F,
        KeyCode::KeyY => 0x10,
        KeyCode::KeyT => 0x11,
        KeyCode::Digit1 => 0x12,
        KeyCode::Digit2 => 0x13,
        KeyCode::Digit3 => 0x14,
        KeyCode::Digit4 => 0x15,
        KeyCode::Digit6 => 0x16,
        KeyCode::Digit5 => 0x17,
        KeyCode::Equal => 0x18,
        KeyCode::Digit9 => 0x19,
        KeyCode::Digit7 => 0x1A,
        KeyCode::Minus => 0x1B,
        KeyCode::Digit8 => 0x1C,
        KeyCode::Digit0 => 0x1D,
        KeyCode::BracketRight => 0x1E,
        KeyCode::KeyO => 0x1F,
        KeyCode::KeyU => 0x20,
        KeyCode::BracketLeft => 0x21,
        KeyCode::KeyI => 0x22,
        KeyCode::KeyP => 0x23,
        KeyCode::Enter => 0x24,
        KeyCode::KeyL => 0x25,
        KeyCode::KeyJ => 0x26,
        KeyCode::Quote => 0x27,
        KeyCode::KeyK => 0x28,
        KeyCode::Semicolon => 0x29,
        KeyCode::Backslash => 0x2A,
        KeyCode::Comma => 0x2B,
        KeyCode::Slash => 0x2C,
        KeyCode::KeyN => 0x2D,
        KeyCode::KeyM => 0x2E,
        KeyCode::Period => 0x2F,
        KeyCode::Tab => 0x30,
        KeyCode::Space => 0x31,
        KeyCode::Backquote => 0x32,
        KeyCode::Backspace => 0x33,
        KeyCode::Escape => 0x35,
        KeyCode::SuperRight => 0x36,
        KeyCode::SuperLeft => 0x37,
        KeyCode::ShiftLeft => 0x38,
        KeyCode::CapsLock => 0x39,
        KeyCode::AltLeft => 0x3A,
        KeyCode::ControlLeft => 0x3B,
        KeyCode::ShiftRight => 0x3C,
        KeyCode::AltRight => 0x3D,
        KeyCode::ControlRight => 0x3E,
        KeyCode::F17 => 0x40,
        KeyCode::NumpadDecimal => 0x41,
        KeyCode::NumpadMultiply => 0x43,
        KeyCode::NumpadAdd => 0x45,
        KeyCode::NumLock => 0x47, // kVK_ANSI_KeypadClear — the position NumLock occupies
        KeyCode::NumpadDivide => 0x4B,
        KeyCode::NumpadEnter => 0x4C,
        KeyCode::NumpadSubtract => 0x4E,
        KeyCode::F18 => 0x4F,
        KeyCode::F19 => 0x50,
        KeyCode::NumpadEqual => 0x51,
        KeyCode::Numpad0 => 0x52,
        KeyCode::Numpad1 => 0x53,
        KeyCode::Numpad2 => 0x54,
        KeyCode::Numpad3 => 0x55,
        KeyCode::Numpad4 => 0x56,
        KeyCode::Numpad5 => 0x57,
        KeyCode::Numpad6 => 0x58,
        KeyCode::Numpad7 => 0x59,
        KeyCode::F20 => 0x5A,
        KeyCode::Numpad8 => 0x5B,
        KeyCode::Numpad9 => 0x5C,
        KeyCode::F5 => 0x60,
        KeyCode::F6 => 0x61,
        KeyCode::F7 => 0x62,
        KeyCode::F3 => 0x63,
        KeyCode::F8 => 0x64,
        KeyCode::F9 => 0x65,
        KeyCode::F11 => 0x67,
        KeyCode::F13 => 0x69,
        KeyCode::F16 => 0x6A,
        KeyCode::F14 => 0x6B,
        KeyCode::F10 => 0x6D,
        KeyCode::ContextMenu => 0x6E,
        KeyCode::F12 => 0x6F,
        KeyCode::F15 => 0x71,
        KeyCode::Insert => 0x72, // kVK_Help — the position Insert occupies on Apple keyboards
        KeyCode::Home => 0x73,
        KeyCode::PageUp => 0x74,
        KeyCode::Delete => 0x75, // kVK_ForwardDelete
        KeyCode::F4 => 0x76,
        KeyCode::End => 0x77,
        KeyCode::F2 => 0x78,
        KeyCode::PageDown => 0x79,
        KeyCode::F1 => 0x7A,
        KeyCode::ArrowLeft => 0x7B,
        KeyCode::ArrowRight => 0x7C,
        KeyCode::ArrowDown => 0x7D,
        KeyCode::ArrowUp => 0x7E,
        _ => 0,
    }
}
