import type {
  AssetEntryDto,
  AssetList as DtoAssetList,
  CommandParamsMap as DtoCommandParamsMap,
  CommandResultMap as DtoCommandResultMap,
  EnvironmentDto,
  ProjectInfoDto,
  ProjectStatusDto,
  RenderStatsDto,
  SelectionResult,
  ThumbnailResult,
  WireUuid,
} from "./sa-types";

export type {
  ActiveAlarmDto,
  ActiveAlarmsDto,
  ControlDiagnosticDto,
  ControlFailureDto,
  VegetationGraphDiagnosticDto,
  VegetationRenderStatsDto,
  VegetationLayerDto,
  VegetationMutationDto,
  VegetationMutationRecordDto,
  VegetationMapChunkDto,
  VegetationMapChunkKeyDto,
  VegetationCookStatusDto,
  AuthoredFieldTileDto,
  FieldChannelDto,
  VegetationEvaluationPreflightDto,
  VegetationNodeEvaluationDiagnosticDto,
  VegetationNodeSchemaDto,
  VegetationTopologyDiffResult,
  WorldBoundsDto,
  WorldCellDto,
  VegetationFamilyRenderDto,
  VegetationCellRenderDto,
  AddEntityParams,
  AlarmEventDto,
  AppManifest,
  ExportAppParams,
  ExportAppResult,
  AnimationClipDto,
  AnimationStateResult,
  AssetMetadataDto,
  AssetUsageDto,
  AssetUsagesParams,
  AssetUsagesResult,
  AssignAssetParams,
  BoneDto,
  AssetCapabilitiesDto,
  AssetModelResult,
  AssetPreviewResult,
  AssetPreviewOptionsResult,
  Camera,
  ComponentBody,
  ComponentList,
  ComponentParams,
  Components,
  Rigidbody,
  Collider,
  KinematicBones,
  CharacterController,
  BVec3,
  PhysicsMaterial,
  PhysicsStateResult,
  PhysicsBodiesResult,
  PhysicsBodyDto,
  DrainContactsResult,
  ContactEventDto,
  WorldHitTargetDto,
  RagdollResult,
  CaptureStartParams,
  CaptureStartResult,
  CaptureStatusResult,
  CaptureStopResult,
  CreateEntityParams,
  CreateAssetFolderParams,
  CreateScriptParams,
  CreateScriptResult,
  DebugOverlaysResult,
  DeleteAssetParams,
  DeleteAssetResult,
  DeleteAssetFolderParams,
  DeselectResult,
  DestroyEntityResult,
  DirectionalLight,
  DrainAlarmsParams,
  DrainAlarmsResult,
  DrainScriptErrorsResult,
  DrainScriptLogsResult,
  EditorCamera,
  EntityList,
  EntityListEntry,
  EntityParams,
  EntityRef,
  EnvironmentProfileListDto,
  EnvironmentProfileSummaryDto,
  FrameHistoryDto,
  FrameHistoryParams,
  FrameSampleDto,
  GetScriptSchemaResult,
  GizmoPointerParams,
  GizmoPointerResult,
  GizmoState,
  ImportModelResult,
  ImportTextureResult,
  ImportLutParams,
  ImportLutResult,
  InspectResult,
  ListClipsResult,
  ClipBindingsResult,
  MorphWeightsResult,
  ListProbesResult,
  MaterialSlot,
  Mesh,
  MoveAssetParams,
  Name,
  OptionalPathParams,
  PathParams,
  PathResult,
  PerfConfigDto,
  PickParams,
  PickResult,
  PickSkeletonJointResult,
  PingParams,
  PingResult,
  PipelineStatsDto,
  PlayStateResult,
  PointLight,
  ProbeRef,
  ProfileCaptureDto,
  ProfileCaptureMetadataDto,
  ProfileSpanDto,
  ProfilerModeResult,
  ProfilerSetModeParams,
  QuitResult,
  RecaptureProbesResult,
  ReflectionProbe,
  RenderPassTimingDto,
  RenderPassTimingsDto,
  RenderQualityResult,
  RenameAssetParams,
  RenameAssetFolderParams,
  RenameEntityParams,
  ScreenshotParams,
  ScreenshotResult,
  Script,
  ScriptErrorDto,
  ScriptLogDto,
  ScriptFieldDto,
  ScriptInputParams,
  ScriptInputResult,
  ScriptSlot,
  ScriptStatusResult,
  SetAaParams,
  SetAaResult,
  SetAtmosphereParams,
  SetCameraParams,
  SetClusteredResult,
  SetComponentFieldParams,
  SetComponentFieldResult,
  SetComponentParams,
  SetComponentResult,
  SetDepthPrepassResult,
  SetEnvironmentParams,
  SaveEnvironmentProfileParams,
  UpdateEnvironmentProfileParams,
  ApplyEnvironmentProfileParams,
  SetExposureParams,
  SetExposureResult,
  SetBloomParams,
  SetBloomResult,
  GradeRangeDto,
  SplitToneDto,
  SetColorGradingParams,
  SetColorGradingResult,
  CreativeLutStat,
  BakeLookParams,
  BakeLookResult,
  SetGiParams,
  SetGiResult,
  SetGizmoParams,
  SetIblResult,
  SetLightParams,
  SetPerfConfigParams,
  UpscaleDto,
  GetUpscaleResult,
  SetUpscaleParams,
  SetUpscaleResult,
  SetProbesParams,
  SetProbesResult,
  SetRenderQualityParams,
  SetRestirResult,
  SetRtShadowsResult,
  SetScriptOverrideParams,
  SetScriptOverrideResult,
  SetShadowsResult,
  SetTransformParams,
  SkeletonOverlayResult,
  SpotLight,
  StepParams,
  ThumbnailParams,
  ToggleParams,
  Transform,
  Vec3,
  Vec4,
  ViewportNativeInfoResult,
  WireUuid,
  BotanicalGraphDto,
} from "./sa-types";

export type Uuid = WireUuid;
export type AssetEntry = AssetEntryDto;
export type AssetList = DtoAssetList;
export type ProjectInfo = ProjectInfoDto;
export type ProjectStatus = ProjectStatusDto;
// The codegen inlines enums into the DTOs that use them (no standalone enum exports), so the phase /
// boot-stage unions are derived from the status DTO's fields — the single source of truth.
export type ProjectPhase = ProjectStatusDto["phase"];
export type BootStage = ProjectStatusDto["stage"];
export type RenderStats = RenderStatsDto;
export type Thumbnail = ThumbnailResult;

export type Environment = EnvironmentDto;
export type Selection = SelectionResult;

export type CommandParamsMap = DtoCommandParamsMap;
export type CommandResultMap = DtoCommandResultMap;
