[package]
name = "xtask"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
saffron-core = { path = "../crates/core" }
saffron-geometry = { path = "../crates/geometry" }
saffron-spatial = { path = "../crates/spatial" }
saffron-vegetation = { path = "../crates/vegetation" }
saffron-protocol = { path = "../crates/protocol" }
saffron-script = { path = "../crates/script" }
anyhow = { workspace = true }
atomic-write-file = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
