use crate::CommandSpec;

/// The typed commands in frozen wire order (`help` excluded — it is the untyped reflective builtin).
pub static COMMANDS: &[CommandSpec] = &[
    CommandSpec::new("ping", "liveness + engine info", "PingParams", "PingResult"),
    CommandSpec::new(
        "render-stats",
        "last frame draw counters",
        "EmptyParams",
        "RenderStatsDto",
    ),
    CommandSpec::new(
        "gpu-scene-stats",
        "persistent GPU-scene mirror population and rebuild counters",
        "EmptyParams",
        "GpuSceneMirrorStatsDto",
    ),
    CommandSpec::new(
        "vegetation-mutate",
        "apply typed vegetation mutations (tombstone/override/anchor/…) through the reducer",
        "VegetationMutateParams",
        "VegetationMutateResult",
    ),
    CommandSpec::new(
        "vegetation-render-stats",
        "per-family and per-cell vegetation render population plus page faults",
        "EmptyParams",
        "VegetationRenderStatsDto",
    ),
    CommandSpec::new(
        "profiler.set-mode",
        "set the GPU profiler mode",
        "ProfilerSetModeParams",
        "ProfilerModeResult",
    ),
    CommandSpec::new(
        "pass-timings",
        "last frame per-pass GPU timings",
        "EmptyParams",
        "RenderPassTimingsDto",
    ),
    CommandSpec::new(
        "profiler.capture-start",
        "arm a bounded profiler capture",
        "CaptureStartParams",
        "CaptureStartResult",
    ),
    CommandSpec::new(
        "profiler.capture-stop",
        "finish + return the armed profiler capture",
        "EmptyParams",
        "CaptureStopResult",
    ),
    CommandSpec::new(
        "profiler.capture-status",
        "non-destructive capture progress",
        "EmptyParams",
        "CaptureStatusResult",
    ),
    CommandSpec::new(
        "frame-history",
        "frame-time percentiles + stutter count",
        "FrameHistoryParams",
        "FrameHistoryDto",
    ),
    CommandSpec::new(
        "get-perf-config",
        "shared frame-budget / threshold config",
        "EmptyParams",
        "PerfConfigDto",
    ),
    CommandSpec::new(
        "set-perf-config",
        "set the frame budget + thresholds",
        "SetPerfConfigParams",
        "PerfConfigDto",
    ),
    CommandSpec::new(
        "get-upscale",
        "TAAU ratio, dynamic-resolution state, and input/display extents",
        "EmptyParams",
        "GetUpscaleResult",
    ),
    CommandSpec::new(
        "set-upscale",
        "set the TAAU input:display ratio + dynamic resolution",
        "SetUpscaleParams",
        "SetUpscaleResult",
    ),
    CommandSpec::new(
        "drain-alarms",
        "drain perf-alarm events (seq cursor)",
        "DrainAlarmsParams",
        "DrainAlarmsResult",
    ),
    CommandSpec::new(
        "list-active-alarms",
        "currently firing perf alarms",
        "EmptyParams",
        "ActiveAlarmsDto",
    ),
    CommandSpec::new(
        "set-aa",
        "set anti-aliasing mode",
        "SetAaParams",
        "SetAaResult",
    ),
    CommandSpec::new(
        "get-taa-params",
        "current TAA blend/sharpen parameters",
        "EmptyParams",
        "GetTaaParamsResult",
    ),
    CommandSpec::new(
        "set-taa-params",
        "tune TAA blend/sharpen parameters (partial update)",
        "SetTaaParamsParams",
        "SetTaaParamsResult",
    ),
    CommandSpec::new(
        "set-view-mode",
        "set the debug render-output mode {lit|wireframe|albedo|normal|roughness|metallic|emissive}",
        "SetViewModeParams",
        "SetViewModeResult",
    ),
    CommandSpec::new(
        "set-clustered",
        "toggle clustered lighting",
        "ToggleParams",
        "SetClusteredResult",
    ),
    CommandSpec::new(
        "set-ibl",
        "toggle image-based lighting",
        "ToggleParams",
        "SetIblResult",
    ),
    CommandSpec::new(
        "set-sky-occlusion",
        "occlude the reflected skybox with the Global SDF reflection-occlusion cone",
        "ToggleParams",
        "SetSkyOcclusionResult",
    ),
    CommandSpec::new(
        "set-gdf",
        "composite per-mesh SDFs into the Global Distance Field cascade clipmap",
        "ToggleParams",
        "SetGdfResult",
    ),
    CommandSpec::new(
        "set-render-quality",
        "set the render-quality tier (low/medium/high/ultra) — the SSGI/GTAO/contact knob",
        "SetRenderQualityParams",
        "RenderQualityResult",
    ),
    CommandSpec::new(
        "get-render-quality",
        "the active render-quality tier + resolved per-effect state",
        "EmptyParams",
        "RenderQualityResult",
    ),
    CommandSpec::new(
        "set-tonemap",
        "set the tonemap operator (reinhard/aces/agx/pbr-neutral)",
        "SetTonemapParams",
        "TonemapResult",
    ),
    CommandSpec::new(
        "set-rt-shadows",
        "toggle ray-traced shadows",
        "ToggleParams",
        "SetRtShadowsResult",
    ),
    CommandSpec::new(
        "set-hierarchy-cut",
        "set-hierarchy-cut {auto|coarse|fine} [camera|shadow|gi] — pin one view's hierarchy cut (omit the cut to read)",
        "SetHierarchyCutParams",
        "HierarchyCutResult",
    ),
    CommandSpec::new(
        "set-mesh-executor",
        "set-mesh-executor [true|false] — route the shaded executor through the mesh stage (omit to read)",
        "SetMeshExecutorParams",
        "MeshExecutorResult",
    ),
    CommandSpec::new(
        "vsm-page-budget",
        "read or set the shadow pages a frame may render",
        "VsmPageBudgetParams",
        "VsmPageBudgetResult",
    ),
    CommandSpec::new(
        "page-request-budget",
        "read or set the missing-page requests one view class may raise per frame",
        "PageRequestBudgetParams",
        "PageRequestBudgetResult",
    ),
    CommandSpec::new(
        "set-restir",
        "toggle ReSTIR",
        "ToggleParams",
        "SetRestirResult",
    ),
    CommandSpec::new(
        "set-ssr",
        "toggle screen-space reflections",
        "ToggleParams",
        "SetSsrResult",
    ),
    CommandSpec::new(
        "set-rt-reflections",
        "toggle ray-traced reflections",
        "ToggleParams",
        "SetRtReflectionsResult",
    ),
    CommandSpec::new("set-gi", "set GI mode", "SetGiParams", "SetGiResult"),
    CommandSpec::new(
        "set-shadows",
        "toggle shadows",
        "ToggleParams",
        "SetShadowsResult",
    ),
    CommandSpec::new(
        "set-skinning",
        "toggle GPU skinning",
        "ToggleParams",
        "SetSkinningResult",
    ),
    CommandSpec::new(
        "set-displacement",
        "toggle GPU displacement",
        "ToggleParams",
        "SetDisplacementResult",
    ),
    CommandSpec::new(
        "set-depth-prepass",
        "toggle depth prepass",
        "ToggleParams",
        "SetDepthPrepassResult",
    ),
    CommandSpec::new(
        "viewport-native-info",
        "native viewport bridge status",
        "EmptyParams",
        "ViewportNativeInfoResult",
    ),
    CommandSpec::new(
        "set-viewport-power-state",
        "set the editor viewport visibility (focused/unfocused/occluded) for idle throttling",
        "SetViewportPowerStateParams",
        "ViewportPowerStateResult",
    ),
    CommandSpec::new(
        "set-viewport-size",
        "set the offscreen render size",
        "SetViewportSizeParams",
        "SetViewportSizeResult",
    ),
    CommandSpec::new(
        "list-entities",
        "list all entities",
        "EmptyParams",
        "EntityList",
    ),
    CommandSpec::new(
        "list-components",
        "list registered component types",
        "EmptyParams",
        "ComponentList",
    ),
    CommandSpec::new(
        "create-entity",
        "create-entity {name}",
        "CreateEntityParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "destroy-entity",
        "destroy-entity {entity}",
        "EntityParams",
        "DestroyEntityResult",
    ),
    CommandSpec::new(
        "set-parent",
        "set-parent {entity, parent?} — reparent (absent/0 parent detaches to root)",
        "SetParentParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "add-component",
        "add-component {entity, component}",
        "ComponentParams",
        "AddComponentResult",
    ),
    CommandSpec::new(
        "remove-component",
        "remove-component {entity, component}",
        "ComponentParams",
        "RemoveComponentResult",
    ),
    CommandSpec::new(
        "set-component",
        "set-component {entity, component, json}",
        "SetComponentParams",
        "SetComponentResult",
    ),
    CommandSpec::new(
        "set-component-order",
        "set-component-order {entity, components}",
        "SetComponentOrderParams",
        "SetComponentOrderResult",
    ),
    CommandSpec::new(
        "set-transform",
        "set-transform {entity, translation?, rotation?, scale?}",
        "SetTransformParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "set-light",
        "set-light {entity?, direction?, color?, intensity?, ambient?}",
        "SetLightParams",
        "EntityRef",
    ),
    CommandSpec::new("select", "select {entity}", "EntityParams", "EntityRef"),
    CommandSpec::new("pick", "pick {u=0.5, v=0.5}", "PickParams", "PickResult"),
    CommandSpec::new(
        "query-surface-ray",
        "query-surface-ray {originM, direction, maxDistanceM?} — nearest scene-surface hit",
        "QuerySurfaceRayParams",
        "SurfaceRayResult",
    ),
    CommandSpec::new(
        "spatial-cell",
        "spatial-cell {world? | ticks?, level?} — canonical position and owner cell",
        "SpatialCellParams",
        "SpatialCellResult",
    ),
    CommandSpec::new(
        "spatial-providers",
        "spatial-providers — list live surface providers and capabilities",
        "EmptyParams",
        "SurfaceProvidersResult",
    ),
    CommandSpec::new(
        "spatial-sample",
        "spatial-sample {provider, channel, position, derivative?}",
        "SpatialSampleParams",
        "SpatialSampleResult",
    ),
    CommandSpec::new(
        "spatial-residency",
        "spatial-residency — list spatial sources and per-facet cell references",
        "EmptyParams",
        "SpatialResidencyResult",
    ),
    CommandSpec::new(
        "inspect",
        "inspect {entity}",
        "EntityParams",
        "InspectResult",
    ),
    CommandSpec::new("focus", "focus {entity}", "EntityParams", "EntityRef"),
    CommandSpec::new(
        "get-world-transform",
        "get-world-transform {entity} — the entity's composed world translation + scale",
        "EntityParams",
        "WorldTransformResult",
    ),
    CommandSpec::new(
        "get-environment",
        "get environment settings",
        "EmptyParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "get-environment-defaults",
        "get the canonical environment defaults",
        "EmptyParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "list-environment-profiles",
        "list built-in and project environment profiles",
        "EmptyParams",
        "EnvironmentProfileListDto",
    ),
    CommandSpec::new(
        "save-environment-profile",
        "save the active environment as a project profile",
        "SaveEnvironmentProfileParams",
        "EnvironmentProfileSummaryDto",
    ),
    CommandSpec::new(
        "update-environment-profile",
        "replace a project profile with the active environment",
        "UpdateEnvironmentProfileParams",
        "EnvironmentProfileSummaryDto",
    ),
    CommandSpec::new(
        "apply-environment-profile",
        "apply a complete environment profile",
        "ApplyEnvironmentProfileParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "set-environment",
        "set environment settings",
        "SetEnvironmentParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "set-atmosphere",
        "set procedural-atmosphere settings",
        "SetAtmosphereParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "set-fog",
        "set analytic height & distance fog settings",
        "SetFogParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "set-clouds",
        "set volumetric cloud shape settings",
        "SetCloudsParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "set-wind",
        "set shared global wind settings",
        "SetWindParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "sample-wind",
        "sample-wind {positionM, timeS?} — the composed wind velocity at a world position",
        "SampleWindParams",
        "SampleWindResult",
    ),
    CommandSpec::new(
        "emit-interaction-impulse",
        "emit-interaction-impulse {positionM, radiusM, strength, direction?, depress?} — push the world interaction field",
        "EmitInteractionImpulseParams",
        "EmitInteractionImpulseResult",
    ),
    CommandSpec::new(
        "wind-interaction-field",
        "wind-interaction-field {cascade?, resolution?} — one whole cascade of the world interaction field, reduced to a grid",
        "WindInteractionFieldParams",
        "WindInteractionFieldResult",
    ),
    CommandSpec::new(
        "set-time-of-day",
        "set calendar-driven time-of-day settings",
        "SetTimeOfDayParams",
        "EnvironmentDto",
    ),
    CommandSpec::new(
        "get-selection",
        "get current selection",
        "EmptyParams",
        "SelectionResult",
    ),
    CommandSpec::new(
        "deselect",
        "clear selection",
        "EmptyParams",
        "DeselectResult",
    ),
    CommandSpec::new(
        "play",
        "enter or resume play mode",
        "EmptyParams",
        "PlayStateResult",
    ),
    CommandSpec::new(
        "pause",
        "pause the running scene",
        "EmptyParams",
        "PlayStateResult",
    ),
    CommandSpec::new(
        "step",
        "step {frames=1} while paused",
        "StepParams",
        "PlayStateResult",
    ),
    CommandSpec::new(
        "stop",
        "stop play and restore the authored scene",
        "EmptyParams",
        "PlayStateResult",
    ),
    CommandSpec::new(
        "get-play-state",
        "current play state",
        "EmptyParams",
        "PlayStateResult",
    ),
    CommandSpec::new(
        "get-animation-state",
        "a rig's playhead, clip, wrap, and speed",
        "AnimationStateParams",
        "AnimationStateResult",
    ),
    CommandSpec::new(
        "list-clips",
        "the animation clips in the project catalog",
        "ListClipsParams",
        "ListClipsResult",
    ),
    CommandSpec::new(
        "play-animation",
        "play a clip on a rig (previews in Edit too)",
        "PlayAnimationParams",
        "AnimationStateResult",
    ),
    CommandSpec::new(
        "set-animation-playing",
        "resume or pause without moving the playhead",
        "SetAnimationPlayingParams",
        "AnimationStateResult",
    ),
    CommandSpec::new(
        "seek-animation",
        "set the playhead (previews in Edit)",
        "SeekAnimationParams",
        "AnimationStateResult",
    ),
    CommandSpec::new(
        "set-animation-loop",
        "set the wrap mode (once|loop|pingpong)",
        "SetAnimationLoopParams",
        "AnimationStateResult",
    ),
    CommandSpec::new(
        "stop-preview",
        "clear the Edit preview and stop (revert to rest)",
        "AnimationStateParams",
        "AnimationStateResult",
    ),
    CommandSpec::new(
        "get-skeleton-overlay",
        "the line-skeleton overlay toggle, axes, and joint size",
        "EmptyParams",
        "SkeletonOverlayResult",
    ),
    CommandSpec::new(
        "set-skeleton-overlay",
        "the selected rig's line-skeleton viewport overlay (show|axes|jointSize)",
        "SetSkeletonOverlayParams",
        "SkeletonOverlayResult",
    ),
    CommandSpec::new(
        "get-debug-overlays",
        "the viewport debug-overlay toggles (bounds|sceneAabb|lightVolumes|grid|colliders)",
        "EmptyParams",
        "DebugOverlaysResult",
    ),
    CommandSpec::new(
        "set-debug-overlays",
        "toggle viewport debug overlays {bounds?, sceneAabb?, lightVolumes?, grid?, colliders?}",
        "DebugOverlaysParams",
        "DebugOverlaysResult",
    ),
    CommandSpec::new(
        "set-skeleton-highlight",
        "tint a previewed model's joint by its get-asset-model node index (-1 clears)",
        "SetSkeletonHighlightParams",
        "SkeletonOverlayResult",
    ),
    CommandSpec::new(
        "pick-skeleton-joint",
        "pick the previewed model's nearest joint to a viewport click (u,v) within radiusPx",
        "PickSkeletonJointParams",
        "PickSkeletonJointResult",
    ),
    CommandSpec::new(
        "set-asset-preview-options",
        "set-asset-preview-options {floor?} — preview-scene settings (show floor)",
        "SetAssetPreviewOptionsParams",
        "AssetPreviewOptionsResult",
    ),
    CommandSpec::new(
        "get-foot-ik",
        "a rig's foot-IK enable, ground height, and chain count",
        "GetFootIkParams",
        "FootIkResult",
    ),
    CommandSpec::new(
        "set-foot-ik",
        "toggle a rig's kinematic foot IK (enabled|groundHeight)",
        "SetFootIkParams",
        "FootIkResult",
    ),
    CommandSpec::new(
        "set-morph-weights",
        "set a morph mesh's blend-shape weights (canonical 0..1)",
        "SetMorphWeightsParams",
        "MorphWeightsResult",
    ),
    CommandSpec::new(
        "get-morph-weights",
        "a morph mesh's live blend-shape weights + target names",
        "GetMorphWeightsParams",
        "MorphWeightsResult",
    ),
    CommandSpec::new(
        "list-clip-bindings",
        "a clip's channels resolved against a live entity forest",
        "ListClipBindingsParams",
        "ClipBindingsResult",
    ),
    CommandSpec::new(
        "get-script-status",
        "play state, live script instances, error high-water",
        "EmptyParams",
        "ScriptStatusResult",
    ),
    CommandSpec::new(
        "physics-state",
        "live physics world summary (active, body + dynamic counts)",
        "EmptyParams",
        "PhysicsStateResult",
    ),
    CommandSpec::new(
        "physics-bodies",
        "every live body's entity, motion, active state, and world position",
        "EmptyParams",
        "PhysicsBodiesResult",
    ),
    CommandSpec::new(
        "fit-collider",
        "re-fit a Collider's shape to the entity's mesh AABB",
        "FitColliderParams",
        "FitColliderResult",
    ),
    CommandSpec::new(
        "apply-impulse",
        "push a Dynamic rigidbody (returns its new velocity)",
        "ApplyImpulseParams",
        "ApplyImpulseResult",
    ),
    CommandSpec::new(
        "drain-contacts",
        "drain contact/trigger events (seq cursor)",
        "DrainContactsParams",
        "DrainContactsResult",
    ),
    CommandSpec::new(
        "set-kinematic-bones",
        "toggle a rig's kinematic-bone physics",
        "SetKinematicBonesParams",
        "KinematicBonesResult",
    ),
    CommandSpec::new(
        "move-character",
        "set a character controller's desired walk velocity",
        "MoveCharacterParams",
        "MoveCharacterResult",
    ),
    CommandSpec::new(
        "raycast",
        "closest physics ray hit (entity/point/normal/distance)",
        "RaycastParams",
        "RaycastResult",
    ),
    CommandSpec::new(
        "shapecast",
        "closest sphere-sweep physics hit",
        "ShapecastParams",
        "RaycastResult",
    ),
    CommandSpec::new(
        "enable-ragdoll",
        "go limp / restore animation on a rig's powered ragdoll",
        "EnableRagdollParams",
        "RagdollResult",
    ),
    CommandSpec::new(
        "set-ragdoll",
        "drive a rig's active-ragdoll blend (motors, body/bone weight)",
        "SetRagdollParams",
        "RagdollResult",
    ),
    CommandSpec::new(
        "get-ragdoll",
        "a rig's ragdoll presence, active flag, and mean blend weight",
        "GetRagdollParams",
        "RagdollResult",
    ),
    CommandSpec::new(
        "drain-script-errors",
        "drain script errors (seq cursor)",
        "DrainScriptErrorsParams",
        "DrainScriptErrorsResult",
    ),
    CommandSpec::new(
        "drain-script-logs",
        "drain sa.log lines (seq cursor)",
        "DrainScriptLogsParams",
        "DrainScriptLogsResult",
    ),
    CommandSpec::new(
        "get-script-schema",
        "a project script's declared fields",
        "GetScriptSchemaParams",
        "GetScriptSchemaResult",
    ),
    CommandSpec::new(
        "set-script-override",
        "write one per-instance script field override",
        "SetScriptOverrideParams",
        "SetScriptOverrideResult",
    ),
    CommandSpec::new(
        "add-entity",
        "add-entity {preset}",
        "AddEntityParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "copy-entity",
        "copy-entity {entity}",
        "EntityParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "rename-entity",
        "rename-entity {entity, name}",
        "RenameEntityParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "set-component-field",
        "set-component-field {entity, component, field, value}",
        "SetComponentFieldParams",
        "SetComponentFieldResult",
    ),
    CommandSpec::new("get-camera", "get camera", "EmptyParams", "EditorCamera"),
    CommandSpec::new(
        "set-camera",
        "set camera",
        "SetCameraParams",
        "EditorCamera",
    ),
    CommandSpec::new("get-gizmo", "get gizmo", "EmptyParams", "GizmoState"),
    CommandSpec::new("set-gizmo", "set gizmo", "SetGizmoParams", "GizmoState"),
    CommandSpec::new(
        "gizmo-pointer",
        "drive gizmo pointer",
        "GizmoPointerParams",
        "GizmoPointerResult",
    ),
    CommandSpec::new(
        "fly-input",
        "stream editor fly-cam input",
        "FlyInputParams",
        "FlyInputResult",
    ),
    CommandSpec::new(
        "script-input",
        "set Lua gameplay key state",
        "ScriptInputParams",
        "ScriptInputResult",
    ),
    CommandSpec::new(
        "set-probes",
        "toggle reflection-probe sampling",
        "SetProbesParams",
        "SetProbesResult",
    ),
    CommandSpec::new(
        "recapture-probes",
        "mark reflection probes dirty",
        "EmptyParams",
        "RecaptureProbesResult",
    ),
    CommandSpec::new(
        "list-probes",
        "list captured reflection probes",
        "EmptyParams",
        "ListProbesResult",
    ),
    CommandSpec::new(
        "set-exposure",
        "set-exposure {ev}",
        "SetExposureParams",
        "SetExposureResult",
    ),
    CommandSpec::new(
        "set-bloom",
        "set-bloom {enabled} {intensity} {scatter} {tint} {threshold}",
        "SetBloomParams",
        "SetBloomResult",
    ),
    CommandSpec::new(
        "set-color-grading",
        "set-color-grading {temperature} {tint} {contrast} {pivot} {saturation} {slope} {offset} {power}",
        "SetColorGradingParams",
        "SetColorGradingResult",
    ),
    CommandSpec::new(
        "bake-look",
        "bake-look [name] — fold grade + view transform + creative LUT into a 33³ .slut",
        "BakeLookParams",
        "BakeLookResult",
    ),
    CommandSpec::new(
        "set-tessellation-quality",
        "set-tessellation-quality [factorCap] [minFactor] [edgeLengthTarget]",
        "SetTessellationQualityParams",
        "SetTessellationQualityResult",
    ),
    CommandSpec::new(
        "vegetation-compile-biome",
        "compile a biome graph and inspect dependencies, halo, estimates, and hard caps",
        "VegetationCompileBiomeParams",
        "VegetationCompileBiomeResult",
    ),
    CommandSpec::new(
        "vegetation-node-schema",
        "inspect typed biome-node pins, parameters, seed namespaces, and execution capability",
        "VegetationNodeSchemaParams",
        "VegetationNodeSchemaResult",
    ),
    CommandSpec::new(
        "vegetation-preflight-region",
        "assemble, comprehensively bound, and retain one biome evaluation without starting a worker",
        "VegetationPreflightRegionParams",
        "VegetationEvaluationJobDto",
    ),
    CommandSpec::new(
        "vegetation-start-evaluation",
        "start the exact evaluator and inputs retained by a prepared vegetation job",
        "VegetationEvaluationJobParams",
        "VegetationEvaluationJobDto",
    ),
    CommandSpec::new(
        "vegetation-evaluation-status",
        "poll an asynchronous vegetation evaluation and its deterministic aggregate",
        "VegetationEvaluationJobParams",
        "VegetationEvaluationStatusDto",
    ),
    CommandSpec::new(
        "vegetation-cancel-evaluation",
        "cancel an asynchronous vegetation evaluation without partial publication",
        "VegetationEvaluationJobParams",
        "VegetationEvaluationStatusDto",
    ),
    CommandSpec::new(
        "vegetation-explain-point",
        "trace an accepted plant or rejected candidate through its provenance decision DAG",
        "VegetationExplainPointParams",
        "ProvenanceExplanationDto",
    ),
    CommandSpec::new(
        "vegetation-cook",
        "start one deterministic content-addressed vegetation cook",
        "VegetationCookParams",
        "VegetationCookJobDto",
    ),
    CommandSpec::new(
        "vegetation-cook-status",
        "poll an asynchronous vegetation cook and its terminal manifest",
        "VegetationCookJobParams",
        "VegetationCookStatusDto",
    ),
    CommandSpec::new(
        "vegetation-cancel-cook",
        "cancel a vegetation cook without publishing partial or superseded output",
        "VegetationCookJobParams",
        "VegetationCookStatusDto",
    ),
    CommandSpec::new(
        "vegetation-cell-inspect",
        "inspect one validated immutable vegetation cell header and section table",
        "VegetationCellInspectParams",
        "VegetationCellInspectResult",
    ),
    CommandSpec::new(
        "vegetation-rejections",
        "one cooked cell's rejected candidates: position, reason, and ordinal (capped rows)",
        "VegetationRejectionsParams",
        "VegetationRejectionsResult",
    ),
    CommandSpec::new(
        "vegetation-topology-diff",
        "diff two cooked manifests per cell: added/removed/moved plants + override conflicts",
        "VegetationTopologyDiffParams",
        "VegetationTopologyDiffResult",
    ),
    CommandSpec::new(
        "vegetation-manifest",
        "inspect the current or one exact immutable vegetation base manifest",
        "VegetationManifestParams",
        "VegetationManifestResult",
    ),
    CommandSpec::new(
        "vegetation-runtime-status",
        "report the exact runtime vegetation generation, state, queues, residency, and budgets",
        "EmptyParams",
        "VegetationRuntimeStatusDto",
    ),
    CommandSpec::new(
        "vegetation-runtime-cell",
        "inspect one immutable CPU-resident vegetation cell generation",
        "VegetationRuntimeCellParams",
        "VegetationRuntimeCellResult",
    ),
    CommandSpec::new(
        "vegetation-runtime-query",
        "query CPU-resident macro vegetation by bounds, radius, ray, or nearest",
        "VegetationRuntimeQueryParams",
        "VegetationRuntimeQueryResult",
    ),
    CommandSpec::new(
        "vegetation-runtime-inspect",
        "inspect one stable plant's effective row, persistent state, and resident provenance",
        "VegetationRuntimePlantParams",
        "VegetationRuntimePlantInspectResult",
    ),
    CommandSpec::new(
        "vegetation-nav-contributions",
        "read vegetation's navigation contributions and the regions awaiting a rebuild",
        "VegetationNavigationParams",
        "VegetationNavigationResult",
    ),
    CommandSpec::new(
        "vegetation-drain-events",
        "read committed vegetation transitions after a cursor",
        "VegetationDrainEventsParams",
        "VegetationDrainEventsResult",
    ),
    CommandSpec::new(
        "vegetation-promote",
        "promote one macro plant to a transient entity view at the next synchronization point",
        "VegetationRuntimePlantParams",
        "VegetationPromotionResult",
    ),
    CommandSpec::new(
        "vegetation-fell",
        "fell one plant: the rooted plant becomes a stump and a separate product entity spawns",
        "VegetationRuntimePlantParams",
        "VegetationPromotionResult",
    ),
    CommandSpec::new(
        "vegetation-demote",
        "demote one promoted plant, writing its state back through the reducer",
        "VegetationRuntimePlantParams",
        "VegetationPromotionResult",
    ),
    CommandSpec::new(
        "vegetation-plant-vitals",
        "read a promoted plant's live biology, replacing the fields that are present",
        "VegetationPlantVitalsParams",
        "VegetationPlantVitalsResult",
    ),
    CommandSpec::new(
        "vegetation-state-export",
        "export the canonical strict runtime vegetation state snapshot",
        "EmptyParams",
        "VegetationStateSnapshotDto",
    ),
    CommandSpec::new(
        "vegetation-state-import",
        "verify and atomically import one exact runtime vegetation state snapshot",
        "VegetationStateImportParams",
        "VegetationStateSnapshotDto",
    ),
    CommandSpec::new(
        "vegetation-advance-ecology",
        "advance biological time and catch dependency regions up to it",
        "VegetationAdvanceEcologyParams",
        "VegetationEcologyReportDto",
    ),
    CommandSpec::new(
        "vegetation-ecology-status",
        "where biological time stands, region by region, with the checkpoint identity",
        "EmptyParams",
        "VegetationEcologyStatusDto",
    ),
    CommandSpec::new(
        "vegetation-ecology-clock",
        "vegetation-ecology-clock {running?, tickMilliseconds?, maxTicksPerSync?, workers?, water?, warmth?} — the world clock biology advances on (omit to read)",
        "VegetationEcologyClockParams",
        "VegetationEcologyClockDto",
    ),
    CommandSpec::new(
        "vegetation-combustion",
        "sample fuel, moisture, health, occupancy, and what is alight in a volume",
        "VegetationCombustionParams",
        "VegetationCombustionDto",
    ),
    CommandSpec::new(
        "vegetation-usd-skeletons",
        "vegetation-usd-skeletons {path} — the UsdSkel skeletons a USD stage declares",
        "UsdSkeletonsParams",
        "UsdSkeletonsResult",
    ),
    CommandSpec::new(
        "vegetation-wind-record",
        "vegetation-wind-record {cell, plant} — one plant's GPU wind prepass record",
        "VegetationWindRecordParams",
        "VegetationWindRecordResult",
    ),
    CommandSpec::new(
        "vegetation-budgets",
        "vegetation-budgets {cellPlants?, familyInstances?, familyMicroPredicted?} — resident-population budgets (omit to read)",
        "VegetationBudgetsParams",
        "VegetationBudgetsResult",
    ),
    CommandSpec::new(
        "vegetation-verify-artifacts",
        "rehash every artifact the current generations name, optionally removing corrupt ones",
        "VegetationVerifyParams",
        "VegetationVerifyResult",
    ),
    CommandSpec::new(
        "vegetation-state-baseline",
        "publish the current runtime vegetation state as the generation's starting state",
        "EmptyParams",
        "VegetationStateBaselineResult",
    ),
    CommandSpec::new(
        "vegetation-telemetry",
        "compact vegetation runtime telemetry: stage times, work counters, resident bytes",
        "EmptyParams",
        "VegetationTelemetryResult",
    ),
    CommandSpec::new(
        "vegetation-network-interest",
        "declare the cells and facets this world is seated with in a network session",
        "VegetationNetworkInterestParams",
        "VegetationNetworkSessionResult",
    ),
    CommandSpec::new(
        "vegetation-network-checkpoint",
        "fingerprint the seated scope at the highest agreed transport sequence",
        "EmptyParams",
        "VegetationNetworkSessionResult",
    ),
    CommandSpec::new(
        "vegetation-import-points",
        "import instanced points from a content-creation tool into an authored map layer",
        "VegetationImportPointsParams",
        "VegetationImportPointsResult",
    ),
    CommandSpec::new(
        "vegetation-export-points",
        "export one authored layer's anchors for a content-creation round trip",
        "VegetationExportPointsParams",
        "VegetationExportPointsResult",
    ),
    CommandSpec::new(
        "plant-create",
        "create a native plant family from the starter botanical graph",
        "PlantCreateParams",
        "PlantCreateResult",
    ),
    CommandSpec::new(
        "plant-graph",
        "read one native plant family's botanical graph and what it grows",
        "PlantGrowthParams",
        "PlantGraphResult",
    ),
    CommandSpec::new(
        "plant-graph-set",
        "replace one native plant family's botanical graph and regrow it",
        "PlantGraphSetParams",
        "PlantGraphResult",
    ),
    CommandSpec::new(
        "plant-growth",
        "what one plant family's botanical graph grows",
        "PlantGrowthParams",
        "BotanicalGrowthDto",
    ),
    CommandSpec::new(
        "plant-proxies",
        "plant-proxies {plant} — the collision and navigation proxies a family derived",
        "PlantProxiesParams",
        "PlantProxiesResult",
    ),
    CommandSpec::new(
        "plant-season-phenotype",
        "plant-season-phenotype {plant, seasonMille, lifecycle?, healthMille?, moistureMille?} — the appearance a family renders then, with every phenotype's weight",
        "PlantSeasonPhenotypeParams",
        "PlantSeasonPhenotypeResult",
    ),
    CommandSpec::new(
        "plant-hierarchy",
        "plant-hierarchy {plant} — the cooked cut: each node's representation, page, and declared error",
        "PlantHierarchyParams",
        "PlantHierarchyResult",
    ),
    CommandSpec::new(
        "plant-atlas",
        "plant-atlas {plant, level?} — one cooked family's packed coverage atlas as a PNG",
        "PlantAtlasParams",
        "PlantAtlasResult",
    ),
    CommandSpec::new(
        "plant-phenotypes",
        "plant-phenotypes {plant, phenotypes?} — read or replace one family's authored appearances",
        "PlantPhenotypesParams",
        "PlantPhenotypesResult",
    ),
    CommandSpec::new(
        "plant-elements",
        "every element of one native plant family a manual edit can address",
        "PlantGrowthParams",
        "PlantElementsResult",
    ),
    CommandSpec::new(
        "plant-validate",
        "validate one authored plant family and inspect its exact sources",
        "PlantValidateParams",
        "PlantValidationResult",
    ),
    CommandSpec::new(
        "plant-recook",
        "normalize and atomically publish one plant family through its retained recipe",
        "PlantRecookParams",
        "PlantRecookResult",
    ),
    CommandSpec::new(
        "get-project",
        "active project metadata",
        "EmptyParams",
        "ProjectInfoDto",
    ),
    CommandSpec::new(
        "project-status",
        "project-load phase + progress",
        "EmptyParams",
        "ProjectStatusDto",
    ),
    CommandSpec::new(
        "cancel-load",
        "abort the in-flight project load",
        "EmptyParams",
        "ProjectStatusDto",
    ),
    CommandSpec::new(
        "new-project",
        "new-project {name}",
        "NewProjectParams",
        "ProjectStatusDto",
    ),
    CommandSpec::new(
        "create-script",
        "boilerplate .lua under the project src/",
        "CreateScriptParams",
        "CreateScriptResult",
    ),
    CommandSpec::new(
        "open-project",
        "open-project {path}",
        "PathParams",
        "ProjectStatusDto",
    ),
    CommandSpec::new(
        "import-model",
        "import-model {path} — optional store attribution",
        "ImportModelParams",
        "ImportModelResult",
    ),
    CommandSpec::new(
        "instantiate-model",
        "instantiate-model {asset} [name]",
        "InstantiateModelParams",
        "EntityRef",
    ),
    CommandSpec::new(
        "asset-placement",
        "asset-placement {phase, asset?, u?, v?} — preview, commit, or clear a viewport model drop",
        "AssetPlacementParams",
        "AssetPlacementResult",
    ),
    CommandSpec::new(
        "import-texture",
        "import-texture {path} [colorspace]",
        "ImportTextureParams",
        "ImportTextureResult",
    ),
    CommandSpec::new(
        "import-lut",
        "import-lut {path} — import a creative .cube look as a LUT asset",
        "ImportLutParams",
        "ImportLutResult",
    ),
    CommandSpec::new(
        "import-vegetation-asset",
        "import-vegetation-asset {path} [folder] — import an authored .splant, .sbiome, or .svegmap package",
        "ImportVegetationAssetParams",
        "ImportVegetationAssetResult",
    ),
    CommandSpec::new(
        "list-assets",
        "list project asset catalog",
        "EmptyParams",
        "AssetList",
    ),
    CommandSpec::new(
        "vegetation-map-layer-commit",
        "commit one optimistic authored-map layer transaction (upserts + removals)",
        "VegetationMapLayerCommitParams",
        "VegetationMapLayerCommitResult",
    ),
    CommandSpec::new(
        "vegetation-map-chunk-commit",
        "commit one optimistic authored-map chunk transaction (a brush gesture's tiles + anchors)",
        "VegetationMapChunkCommitParams",
        "VegetationMapChunkCommitResult",
    ),
    CommandSpec::new(
        "vegetation-map-chunk-read",
        "read authored map chunks by logical key (a brush gesture's read-modify-write baseline)",
        "VegetationMapChunkReadParams",
        "VegetationMapChunkReadResult",
    ),
    CommandSpec::new(
        "vegetation-asset-summary",
        "vegetation-asset-summary {asset} — inspect an authored plant, biome, or vegetation map",
        "VegetationAssetSummaryParams",
        "VegetationAssetSummaryResult",
    ),
    CommandSpec::new(
        "scan-assets",
        "rescan assets/ and reconcile the catalog from disk",
        "EmptyParams",
        "ScanAssetsResult",
    ),
    CommandSpec::new(
        "extract-subasset",
        "extract-subasset {asset, subAsset} [dest] — slice an embedded sub-asset to a standalone file",
        "ExtractSubAssetParams",
        "AssetRef",
    ),
    CommandSpec::new(
        "clear-extraction",
        "clear-extraction {asset, subAsset} — revert an extracted sub-asset to the embedded chunk",
        "ClearExtractionParams",
        "AssetRef",
    ),
    CommandSpec::new(
        "reimport-model",
        "reimport-model {asset} — re-bake from source (skip if unchanged), preserving extractions",
        "ReimportModelParams",
        "ReimportModelResult",
    ),
    CommandSpec::new(
        "model-info",
        "model-info {asset} — a container's sub-assets, source recipe, and byte footprint",
        "ModelInfoParams",
        "ModelInfoResult",
    ),
    CommandSpec::new(
        "asset-references",
        "asset-references {asset} — what references this / what this references + footprint",
        "AssetReferencesParams",
        "AssetReferencesResult",
    ),
    CommandSpec::new(
        "get-asset-model",
        "get-asset-model {asset} — a model's capabilities + bone tree + clips, from its .smodel container",
        "GetAssetModelParams",
        "AssetModelResult",
    ),
    CommandSpec::new(
        "enter-asset-preview",
        "enter-asset-preview {asset} — open any model in an isolated preview scene",
        "EnterAssetPreviewParams",
        "AssetPreviewResult",
    ),
    CommandSpec::new(
        "exit-asset-preview",
        "exit-asset-preview — close the asset preview and restore the authored scene + camera",
        "EmptyParams",
        "PlayStateResult",
    ),
    CommandSpec::new(
        "set-active-view",
        "set-active-view {view} — switch the rendered view (scene | assetPreview)",
        "SetActiveViewParams",
        "SetActiveViewResult",
    ),
    CommandSpec::new(
        "clean-assets",
        "clean-assets [exclude] — categorized cleanup report (dry-run; never deletes)",
        "CleanAssetsParams",
        "CleanReport",
    ),
    CommandSpec::new(
        "delete-unused",
        "delete-unused {ids} {confirm} — delete confirmed-unused assets, then rescan",
        "DeleteUnusedParams",
        "DeleteUnusedResult",
    ),
    CommandSpec::new(
        "rename-asset",
        "rename-asset {asset, name}",
        "RenameAssetParams",
        "AssetRef",
    ),
    CommandSpec::new(
        "create-asset-folder",
        "create virtual asset folder",
        "CreateAssetFolderParams",
        "AssetList",
    ),
    CommandSpec::new(
        "rename-asset-folder",
        "rename virtual asset folder",
        "RenameAssetFolderParams",
        "AssetList",
    ),
    CommandSpec::new(
        "delete-asset-folder",
        "delete virtual asset folder",
        "DeleteAssetFolderParams",
        "AssetList",
    ),
    CommandSpec::new(
        "move-asset",
        "move asset to virtual folder",
        "MoveAssetParams",
        "AssetRef",
    ),
    CommandSpec::new(
        "asset-usages",
        "list scene usages of an asset",
        "AssetUsagesParams",
        "AssetUsagesResult",
    ),
    CommandSpec::new(
        "probe-asset",
        "probe asset metadata (size, vertices, created)",
        "AssetMetadataParams",
        "AssetMetadataDto",
    ),
    CommandSpec::new(
        "delete-asset",
        "delete asset",
        "DeleteAssetParams",
        "DeleteAssetResult",
    ),
    CommandSpec::new(
        "assign-asset",
        "assign asset to entity",
        "AssignAssetParams",
        "AssignAssetResult",
    ),
    CommandSpec::new(
        "material-create",
        "material-create {name} [from-entity]",
        "MaterialCreateParams",
        "MaterialCreateResult",
    ),
    CommandSpec::new(
        "material-assign",
        "material-assign {entity, material}",
        "MaterialAssignParams",
        "MaterialAssignResult",
    ),
    CommandSpec::new(
        "material-import",
        "material-import {path} [name]",
        "MaterialImportParams",
        "MaterialImportResultDto",
    ),
    CommandSpec::new(
        "material-list",
        "material-list",
        "EmptyParams",
        "MaterialListResult",
    ),
    CommandSpec::new(
        "material-get",
        "material-get {id|name}",
        "MaterialGetParams",
        "MaterialGetResult",
    ),
    CommandSpec::new(
        "material-schema",
        "material-schema {id|name} — the material's exposed override parameters",
        "MaterialSchemaParams",
        "MaterialSchemaResult",
    ),
    CommandSpec::new(
        "material-update",
        "material-update {id} [fields]",
        "MaterialUpdateParams",
        "MaterialUpdateResult",
    ),
    CommandSpec::new(
        "material-set-graph",
        "material-set-graph {material, graph}",
        "MaterialSetGraphParams",
        "MaterialSetGraphResult",
    ),
    CommandSpec::new(
        "material-create-instance",
        "material-create-instance {parent} [name]",
        "MaterialCreateInstanceParams",
        "MaterialCreateResult",
    ),
    CommandSpec::new(
        "material-set-override",
        "material-set-override {material, field, value}",
        "MaterialSetOverrideParams",
        "MaterialSetOverrideResult",
    ),
    CommandSpec::new(
        "material-compile-graph",
        "material-compile-graph {material}",
        "MaterialCompileParams",
        "MaterialCompileResult",
    ),
    CommandSpec::new(
        "material-cook",
        "material-cook",
        "EmptyParams",
        "MaterialCookResult",
    ),
    CommandSpec::new(
        "save-scene",
        "save-scene {path}",
        "PathParams",
        "PathResult",
    ),
    CommandSpec::new(
        "load-scene",
        "load-scene {path}",
        "PathParams",
        "PathResult",
    ),
    CommandSpec::new(
        "save-project",
        "save active project",
        "OptionalPathParams",
        "ProjectInfoDto",
    ),
    CommandSpec::new(
        "load-project",
        "load-project {path}",
        "OptionalPathParams",
        "ProjectStatusDto",
    ),
    CommandSpec::new(
        "reload-project",
        "reload the active project",
        "EmptyParams",
        "ProjectStatusDto",
    ),
    CommandSpec::new(
        "get-stores",
        "get-stores — enabled asset-store connectors for the project",
        "EmptyParams",
        "ProjectStoresDto",
    ),
    CommandSpec::new(
        "set-stores",
        "set-stores {enabled} — set the project's enabled asset-store connectors",
        "ProjectStoresDto",
        "ProjectStoresDto",
    ),
    CommandSpec::new(
        "screenshot",
        "capture screenshot",
        "ScreenshotParams",
        "ScreenshotResult",
    ),
    CommandSpec::new(
        "get-thumbnail",
        "get asset thumbnail",
        "ThumbnailParams",
        "ThumbnailResult",
    ),
    CommandSpec::new(
        "view-asset",
        "view asset thumbnail",
        "ThumbnailParams",
        "ThumbnailResult",
    ),
    CommandSpec::new(
        "thumbnail-cache",
        "inspect or empty the thumbnail disk cache",
        "ThumbnailCacheParams",
        "ThumbnailCacheResult",
    ),
    CommandSpec::new(
        "export-app",
        "export-app {outputDir, app} — cook the project into a platform-native application",
        "ExportAppParams",
        "ExportAppResult",
    ),
    CommandSpec::new("quit", "close the running app", "EmptyParams", "QuitResult"),
];
