use std::sync::Arc;

use ash::vk;
use vk_mem::Alloc;

use super::barriers::{
    copy_buffer_to_image, copy_buffer_to_image_mip, record_texture_upload, transition_image,
    transition_image_layers,
};
use super::staging::StagingBuffer;
use super::{Uploader, float_to_half};
use crate::descriptors::Descriptors;
use crate::resources::{GpuTexture, GpuTextureParts, Image, ImageDesc, MinMaxPyramid};
use crate::{Error, Result, checked};

/// One prefiltered RGBA8 mip supplied to [`Uploader::upload_texture_mips`].
#[derive(Clone, Copy, Debug)]
pub struct TextureMipLevel<'a> {
    /// Tightly packed RGBA8 texels.
    pub rgba: &'a [u8],
    /// Level width.
    pub width: u32,
    /// Level height.
    pub height: u32,
}

fn valid_prefiltered_mip_chain(mips: &[TextureMipLevel<'_>]) -> bool {
    let Some(base) = mips.first() else {
        return false;
    };
    base.width != 0
        && base.height != 0
        && mips.len() == mip_count(base.width, base.height) as usize
        && mips.iter().enumerate().all(|(level, mip)| {
            let expected_bytes = (mip.width as usize)
                .checked_mul(mip.height as usize)
                .and_then(|texels| texels.checked_mul(4));
            mip.width == base.width.checked_shr(level as u32).unwrap_or(0).max(1)
                && mip.height == base.height.checked_shr(level as u32).unwrap_or(0).max(1)
                && expected_bytes == Some(mip.rgba.len())
        })
}

/// A freshly created device-local sampled image awaiting its view + bindless slot —
/// the handoff from [`Uploader::create_sampled_image`] to
/// [`Uploader::finish_texture`]. Owns the image until `finish_texture` wraps it in a
/// [`GpuTexture`] (or an upload-recording failure frees it directly).
struct UploadedImage {
    image: vk::Image,
    allocation: vk_mem::Allocation,
    width: u32,
    height: u32,
    format: vk::Format,
    mip_levels: u32,
}

/// Full mip-chain length for a `width × height` image (down to 1×1).
pub(super) fn mip_count(width: u32, height: u32) -> u32 {
    let mut d = width.max(height);
    let mut levels = 1;
    while d > 1 {
        d >>= 1;
        levels += 1;
    }
    levels
}

impl Uploader {
    /// Uploads tightly packed RGBA8 pixels as a sampled, mipmapped texture in the
    /// bindless array, claiming a slot in `descriptors` and writing the view into it.
    ///
    /// `srgb` selects `R8G8B8A8_SRGB` (color) vs `R8G8B8A8_UNORM` (data). A full mip
    /// chain is generated by blitting down from mip 0.
    ///
    /// # Errors
    ///
    /// Returns [`Error::ZeroSizedImage`] for a zero extent or [`Error::Vk`] for a
    /// failing Vulkan/VMA call; allocated resources are freed before return on error.
    pub fn upload_texture(
        &self,
        descriptors: &Descriptors,
        rgba: &[u8],
        width: u32,
        height: u32,
        srgb: bool,
    ) -> Result<Arc<GpuTexture>> {
        let format = if srgb {
            vk::Format::R8G8B8A8_SRGB
        } else {
            vk::Format::R8G8B8A8_UNORM
        };
        self.upload_mipped_rgba8(descriptors, rgba, (width, height), format, "upload_texture")
    }

    /// Stages `rgba` into a `format` image with a blitted mip chain and finishes it into a
    /// bindless slot. Every resource allocated before a failure is freed before returning.
    fn upload_mipped_rgba8(
        &self,
        descriptors: &Descriptors,
        rgba: &[u8],
        extent: (u32, u32),
        format: vk::Format,
        label: &'static str,
    ) -> Result<Arc<GpuTexture>> {
        let uploaded = self.stage_mipped_rgba8(rgba, extent, format, label)?;
        self.finish_texture(descriptors, uploaded, None)
    }

    /// Stages `rgba` into a `format` image, blits its full mip chain, and leaves it in
    /// `SHADER_READ_ONLY` — the shared front half of every mipped RGBA8 upload.
    fn stage_mipped_rgba8(
        &self,
        rgba: &[u8],
        extent: (u32, u32),
        format: vk::Format,
        label: &'static str,
    ) -> Result<UploadedImage> {
        let (width, height) = extent;
        if width == 0 || height == 0 {
            return Err(Error::ZeroSizedImage);
        }
        let bytes = (width as vk::DeviceSize) * (height as vk::DeviceSize) * 4;
        let mip_levels = mip_count(width, height);

        let mut staging = StagingBuffer::new(self.allocator(), bytes)?;
        staging.mapped_slice()[..bytes as usize].copy_from_slice(&rgba[..bytes as usize]);
        staging.flush();
        let uploaded = self.create_sampled_image(width, height, mip_levels, format)?;
        let image = uploaded.image;
        let recorded = self.with_one_off_commands(label, |cmd| {
            // SAFETY: the ash seam. The image/staging buffer outlive the submit-wait.
            unsafe {
                record_texture_upload(
                    self.raw(),
                    cmd,
                    image,
                    staging.handle(),
                    width,
                    height,
                    mip_levels,
                );
            }
        });
        drop(staging);
        match recorded {
            Ok(()) => Ok(uploaded),
            Err(err) => {
                self.destroy_image(uploaded.image, uploaded.allocation);
                Err(err)
            }
        }
    }

    /// Uploads an explicit, prefiltered RGBA8 mip chain into one bindless texture.
    ///
    /// This is the canonical coverage path: every level is CPU-derived and copied
    /// exactly, so driver blit filtering cannot change thin-sheet classification.
    ///
    /// # Errors
    ///
    /// Returns [`Error::ZeroSizedImage`] for an empty/malformed chain or [`Error::Vk`]
    /// for a failing Vulkan/VMA operation.
    pub fn upload_texture_mips(
        &self,
        descriptors: &Descriptors,
        mips: &[TextureMipLevel<'_>],
        srgb: bool,
    ) -> Result<Arc<GpuTexture>> {
        let Some(base) = mips.first() else {
            return Err(Error::ZeroSizedImage);
        };
        if !valid_prefiltered_mip_chain(mips) {
            return Err(Error::ZeroSizedImage);
        }
        let total = mips.iter().map(|mip| mip.rgba.len()).sum::<usize>();
        let mut staging = StagingBuffer::new(self.allocator(), total as vk::DeviceSize)?;
        let mut offsets = Vec::with_capacity(mips.len());
        let mut offset = 0_usize;
        for mip in mips {
            offsets.push(offset as vk::DeviceSize);
            staging.mapped_slice()[offset..offset + mip.rgba.len()].copy_from_slice(mip.rgba);
            offset += mip.rgba.len();
        }
        staging.flush();

        let format = if srgb {
            vk::Format::R8G8B8A8_SRGB
        } else {
            vk::Format::R8G8B8A8_UNORM
        };
        let uploaded =
            self.create_sampled_image(base.width, base.height, mips.len() as u32, format)?;
        let image = uploaded.image;
        let recorded = self.with_one_off_commands("upload_texture_mips", |cmd| {
            // SAFETY: the image/staging buffer and mip slices outlive the submit-wait.
            unsafe {
                transition_image(
                    self.raw(),
                    cmd,
                    image,
                    mips.len() as u32,
                    vk::ImageLayout::UNDEFINED,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::PipelineStageFlags2::TOP_OF_PIPE,
                    vk::AccessFlags2::empty(),
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                );
                for (level, (mip, &mip_offset)) in mips.iter().zip(&offsets).enumerate() {
                    copy_buffer_to_image_mip(
                        self.raw(),
                        cmd,
                        staging.handle(),
                        image,
                        mip_offset,
                        level as u32,
                        vk::Extent2D {
                            width: mip.width,
                            height: mip.height,
                        },
                    );
                }
                transition_image(
                    self.raw(),
                    cmd,
                    image,
                    mips.len() as u32,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL,
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                    vk::PipelineStageFlags2::FRAGMENT_SHADER,
                    vk::AccessFlags2::SHADER_SAMPLED_READ,
                );
            }
        });
        drop(staging);
        if let Err(error) = recorded {
            self.destroy_image(uploaded.image, uploaded.allocation);
            return Err(error);
        }
        self.finish_texture(descriptors, uploaded, None)
    }

    /// Uploads the 1×1 white RGBA8 texture and seeds it into *every* bindless slot,
    /// returning the [`GpuTexture`] the renderer holds for its lifetime.
    ///
    /// A material with no albedo/ORM texture indexes [`crate::DEFAULT_WHITE_SLOT`], and
    /// sampling an unbound slot faults on lavapipe (undefined behaviour on real hardware), so
    /// every slot of the partially-bound array is seeded. White leaves the missing-texture
    /// factors unchanged (white × factor = factor).
    ///
    /// # Errors
    ///
    /// Returns [`Error::Vk`] for a failing Vulkan/VMA call during the texture upload.
    pub fn upload_default_white(&self, descriptors: &Descriptors) -> Result<Arc<GpuTexture>> {
        let white = self.upload_texture(descriptors, &[255u8, 255, 255, 255], 1, 1, false)?;
        descriptors.seed_all_textures(white.view());
        Ok(white)
    }

    /// Uploads tightly packed linear-float RGBA (`width*height*4` floats) as an
    /// `R16G16B16A16_SFLOAT` sampled texture in the bindless array, narrowing f32→f16
    /// on the CPU before staging (HDR panoramas / env sources). Single mip.
    ///
    /// # Errors
    ///
    /// Returns [`Error::ZeroSizedImage`] for a zero extent or [`Error::Vk`] for a
    /// failing Vulkan/VMA call; allocated resources are freed before return on error.
    pub fn upload_texture_float(
        &self,
        descriptors: &Descriptors,
        rgba: &[f32],
        width: u32,
        height: u32,
    ) -> Result<Arc<GpuTexture>> {
        if width == 0 || height == 0 {
            return Err(Error::ZeroSizedImage);
        }
        let texels = (width as usize) * (height as usize) * 4;
        let half: Vec<u16> = rgba[..texels].iter().copied().map(float_to_half).collect();
        let bytes = (texels * std::mem::size_of::<u16>()) as vk::DeviceSize;

        let mut staging = StagingBuffer::new(self.allocator(), bytes)?;
        staging.mapped_slice()[..bytes as usize].copy_from_slice(bytemuck::cast_slice(&half));
        staging.flush();

        let format = vk::Format::R16G16B16A16_SFLOAT;
        let uploaded = self.create_sampled_image(width, height, 1, format)?;
        let image = uploaded.image;

        let recorded = self.with_one_off_commands("upload_texture_float", |cmd| {
            // SAFETY: the ash seam. The image/staging buffer outlive the submit-wait.
            unsafe {
                let raw = self.raw();
                transition_image(
                    raw,
                    cmd,
                    image,
                    1,
                    vk::ImageLayout::UNDEFINED,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::PipelineStageFlags2::TOP_OF_PIPE,
                    vk::AccessFlags2::empty(),
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                );
                copy_buffer_to_image(raw, cmd, staging.handle(), image, width, height);
                transition_image(
                    raw,
                    cmd,
                    image,
                    1,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL,
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                    vk::PipelineStageFlags2::FRAGMENT_SHADER,
                    vk::AccessFlags2::SHADER_SAMPLED_READ,
                );
            }
        });
        drop(staging);
        if let Err(err) = recorded {
            self.destroy_image(uploaded.image, uploaded.allocation);
            return Err(err);
        }

        self.finish_texture(descriptors, uploaded, None)
    }

    /// Uploads six tightly packed linear-float RGBA faces into a sampled HDR cube.
    ///
    /// Faces use Vulkan cube order `+X, -X, +Y, -Y, +Z, -Z`; each carries `size²` texels.
    pub fn upload_cube_float(&self, rgba: &[f32], size: u32) -> Result<Image> {
        if size == 0 {
            return Err(Error::ZeroSizedImage);
        }
        let texels = size as usize * size as usize * 6 * 4;
        if rgba.len() < texels {
            return Err(Error::InvalidUploadData(format!(
                "cube upload expected {texels} floats, received {}",
                rgba.len()
            )));
        }
        let half: Vec<u16> = rgba[..texels].iter().copied().map(float_to_half).collect();
        let bytes = (half.len() * std::mem::size_of::<u16>()) as vk::DeviceSize;
        let mut staging = StagingBuffer::new(self.allocator(), bytes)?;
        staging
            .mapped_slice()
            .copy_from_slice(bytemuck::cast_slice(&half));
        staging.flush();

        let desc = ImageDesc {
            extent: vk::Extent2D {
                width: size,
                height: size,
            },
            format: vk::Format::R16G16B16A16_SFLOAT,
            usage: vk::ImageUsageFlags::TRANSFER_DST | vk::ImageUsageFlags::SAMPLED,
            aspect: vk::ImageAspectFlags::COLOR,
            view_type: vk::ImageViewType::CUBE,
            mip_levels: 1,
            array_layers: 6,
            samples: vk::SampleCountFlags::TYPE_1,
        };
        let mut image = Image::new(&self.resources, &desc)?;
        let handle = image.handle();
        let recorded = self.with_one_off_commands("upload_cube_float", |cmd| {
            // SAFETY: the cube and staging buffer outlive the waited one-off submit.
            unsafe {
                transition_image_layers(
                    self.raw(),
                    cmd,
                    handle,
                    6,
                    vk::ImageLayout::UNDEFINED,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::PipelineStageFlags2::TOP_OF_PIPE,
                    vk::AccessFlags2::empty(),
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                );
                let region = vk::BufferImageCopy::default()
                    .image_subresource(vk::ImageSubresourceLayers {
                        aspect_mask: vk::ImageAspectFlags::COLOR,
                        mip_level: 0,
                        base_array_layer: 0,
                        layer_count: 6,
                    })
                    .image_extent(vk::Extent3D {
                        width: size,
                        height: size,
                        depth: 1,
                    });
                self.raw().cmd_copy_buffer_to_image(
                    cmd,
                    staging.handle(),
                    handle,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    &[region],
                );
                transition_image_layers(
                    self.raw(),
                    cmd,
                    handle,
                    6,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL,
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                    vk::PipelineStageFlags2::FRAGMENT_SHADER,
                    vk::AccessFlags2::SHADER_SAMPLED_READ,
                );
            }
        });
        drop(staging);
        recorded?;
        image.layout = vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL;
        Ok(image)
    }

    /// Uploads an RGBA8 image as a sampled, mipmapped **displacement height** texture *and* builds its
    /// per-height min/max pyramid on the GPU, writing both into the same bindless slot (the texture at
    /// binding 0, the pyramid at binding 4). Mirrors [`Uploader::upload_texture`] with `srgb = false`
    /// (height is linear data); the pyramid lets the tessellation factor kernel refine per-region.
    ///
    /// # Errors
    ///
    /// Returns [`Error::ZeroSizedImage`] for a zero extent or [`Error::Vk`] for a failing Vulkan/VMA
    /// call; allocated resources are freed before return on error.
    pub fn upload_height_texture(
        &self,
        descriptors: &Descriptors,
        rgba: &[u8],
        width: u32,
        height: u32,
    ) -> Result<Arc<GpuTexture>> {
        let uploaded = self.stage_mipped_rgba8(
            rgba,
            (width, height),
            vk::Format::R8G8B8A8_UNORM,
            "upload_height_texture",
        )?;
        let pyramid = match self.build_height_pyramid(uploaded.image, width, height) {
            Ok(pyramid) => pyramid,
            Err(err) => {
                self.destroy_image(uploaded.image, uploaded.allocation);
                return Err(err);
            }
        };
        self.finish_texture(descriptors, uploaded, Some(pyramid))
    }

    /// Frees a not-yet-owned [`MinMaxPyramid`] on an upload error path (before a `GpuTexture` takes it).
    fn free_pyramid(&self, pyramid: MinMaxPyramid) {
        // SAFETY: the ash/VMA seam. The view/image were created here and not yet owned; freed once.
        unsafe { self.raw().destroy_image_view(pyramid.view, None) };
        self.destroy_image(pyramid.image, pyramid.allocation);
    }

    /// Uploads the default 1×1 `(0, 0)` min/max pyramid and seeds it into *every*
    /// `heightMinMaxTextures` slot (binding 4), returning the holder the renderer keeps for its
    /// lifetime. A non-displacement texture's slot keeps this default (zero local range → no extra
    /// tessellation refinement); a displacement height map overwrites its slot with its real pyramid.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Vk`]/[`Error::ZeroSizedImage`] for a failing Vulkan/VMA call.
    pub fn upload_default_height_minmax(
        &self,
        descriptors: &Descriptors,
    ) -> Result<crate::resources::DefaultHeightMinMax> {
        let bytes = std::mem::size_of::<[f32; 2]>() as vk::DeviceSize;
        let mut staging = StagingBuffer::new(self.allocator(), bytes)?;
        staging.mapped_slice()[..bytes as usize]
            .copy_from_slice(bytemuck::cast_slice(&[0.0f32, 0.0]));
        staging.flush();

        let uploaded = self.create_sampled_image(1, 1, 1, vk::Format::R32G32_SFLOAT)?;
        let image = uploaded.image;
        let recorded = self.with_one_off_commands("upload_default_height_minmax", |cmd| {
            // SAFETY: the ash seam. The image/staging buffer outlive the submit-wait.
            unsafe {
                let raw = self.raw();
                transition_image(
                    raw,
                    cmd,
                    image,
                    1,
                    vk::ImageLayout::UNDEFINED,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::PipelineStageFlags2::TOP_OF_PIPE,
                    vk::AccessFlags2::empty(),
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                );
                copy_buffer_to_image(raw, cmd, staging.handle(), image, 1, 1);
                transition_image(
                    raw,
                    cmd,
                    image,
                    1,
                    vk::ImageLayout::TRANSFER_DST_OPTIMAL,
                    vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL,
                    vk::PipelineStageFlags2::COPY,
                    vk::AccessFlags2::TRANSFER_WRITE,
                    vk::PipelineStageFlags2::COMPUTE_SHADER,
                    vk::AccessFlags2::SHADER_SAMPLED_READ,
                );
            }
        });
        drop(staging);
        if let Err(err) = recorded {
            self.destroy_image(uploaded.image, uploaded.allocation);
            return Err(err);
        }

        let view_info = vk::ImageViewCreateInfo::default()
            .image(image)
            .view_type(vk::ImageViewType::TYPE_2D)
            .format(vk::Format::R32G32_SFLOAT)
            .subresource_range(vk::ImageSubresourceRange {
                aspect_mask: vk::ImageAspectFlags::COLOR,
                base_mip_level: 0,
                level_count: 1,
                base_array_layer: 0,
                layer_count: 1,
            });
        // SAFETY: the ash seam. The view references the default image just uploaded.
        let view = match unsafe { self.raw().create_image_view(&view_info, None) } {
            Ok(view) => view,
            Err(result) => {
                self.destroy_image(uploaded.image, uploaded.allocation);
                return Err(Error::Vk {
                    context: "create_image_view (default min/max)",
                    result,
                });
            }
        };
        descriptors.seed_all_height_minmax(view);
        Ok(crate::resources::DefaultHeightMinMax::from_parts(
            &self.resources,
            image,
            view,
            uploaded.allocation,
        ))
    }

    /// Creates a device-local sampled image (`TRANSFER_DST | TRANSFER_SRC | SAMPLED`,
    /// dedicated memory), the shared image shape of both texture upload paths.
    fn create_sampled_image(
        &self,
        width: u32,
        height: u32,
        mip_levels: u32,
        format: vk::Format,
    ) -> Result<UploadedImage> {
        let info = vk::ImageCreateInfo::default()
            .image_type(vk::ImageType::TYPE_2D)
            .format(format)
            .extent(vk::Extent3D {
                width,
                height,
                depth: 1,
            })
            .mip_levels(mip_levels)
            .array_layers(1)
            .samples(vk::SampleCountFlags::TYPE_1)
            .tiling(vk::ImageTiling::OPTIMAL)
            .usage(
                vk::ImageUsageFlags::TRANSFER_DST
                    | vk::ImageUsageFlags::TRANSFER_SRC
                    | vk::ImageUsageFlags::SAMPLED,
            )
            .initial_layout(vk::ImageLayout::UNDEFINED);
        let alloc_info = vk_mem::AllocationCreateInfo {
            usage: vk_mem::MemoryUsage::Auto,
            flags: vk_mem::AllocationCreateFlags::DEDICATED_MEMORY,
            ..Default::default()
        };
        // SAFETY: the VMA seam. The create-infos are valid; the image is owned and
        // freed by the returned `GpuTexture` (or `destroy_image` on a later failure).
        let (image, allocation) = checked(
            unsafe { self.allocator().create_image(&info, &alloc_info) },
            "vmaCreateImage (texture)",
        )?;
        Ok(UploadedImage {
            image,
            allocation,
            width,
            height,
            format,
            mip_levels,
        })
    }

    /// Creates the sampled view, claims a bindless slot, writes the texture into the
    /// global set, and wraps the image as a [`GpuTexture`] owning that slot. When `min_max` is
    /// present (a displacement height map) the pyramid is written into binding 4 at the same slot, so
    /// the factor kernel's `heightIndex` addresses both, and the [`GpuTexture`] owns it.
    fn finish_texture(
        &self,
        descriptors: &Descriptors,
        uploaded: UploadedImage,
        min_max: Option<MinMaxPyramid>,
    ) -> Result<Arc<GpuTexture>> {
        let UploadedImage {
            image,
            allocation,
            width,
            height,
            format,
            mip_levels,
        } = uploaded;
        let view_info = vk::ImageViewCreateInfo::default()
            .image(image)
            .view_type(vk::ImageViewType::TYPE_2D)
            .format(format)
            .subresource_range(vk::ImageSubresourceRange {
                aspect_mask: vk::ImageAspectFlags::COLOR,
                base_mip_level: 0,
                level_count: mip_levels,
                base_array_layer: 0,
                layer_count: 1,
            });
        // SAFETY: the ash seam. The view references the image just uploaded.
        let view = match unsafe { self.raw().create_image_view(&view_info, None) } {
            Ok(view) => view,
            Err(result) => {
                self.destroy_image(image, allocation);
                return Err(Error::Vk {
                    context: "create_image_view (texture)",
                    result,
                });
            }
        };

        // Claim a bindless slot (reusing a reclaimed one) and write the texture in. A full
        // array skips the upload (freeing the image + any pyramid) rather than writing out of range.
        let Some(index) = descriptors.claim_slot() else {
            tracing::warn!(
                "albedo bindless array full ({}), texture skipped",
                descriptors.texture_capacity()
            );
            // SAFETY: the ash seam. The view was created above and not yet owned by a
            // `GpuTexture`; free it once on this array-full path before the image.
            unsafe { self.raw().destroy_image_view(view, None) };
            self.destroy_image(image, allocation);
            if let Some(pyramid) = min_max {
                self.free_pyramid(pyramid);
            }
            return Err(Error::BindlessFull("albedo texture"));
        };
        descriptors.write_texture(view, index);
        if let Some(pyramid) = &min_max {
            descriptors.write_height_minmax(pyramid.view, index);
        }

        let texture = GpuTexture::from_parts(
            &self.resources,
            GpuTextureParts {
                image,
                view,
                allocation,
                bindless_index: index,
                extent: vk::Extent2D { width, height },
                format,
                mip_count: mip_levels,
                min_max,
            },
            descriptors.free_list(),
        );
        Ok(Arc::new(texture))
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use super::*;
    use crate::resources::BindlessFreeList;
    use crate::upload::fixtures::device_or_skip;
    use crate::validation_issue_count;

    /// Uploading an RGBA8 texture (with a full mip chain) and an HDR float texture
    /// each claim a bindless slot, write the view into the global set, and are
    /// validation-clean — the phase's GPU upload smoke. The texture drop returns its
    /// slot to the shared free-list. Skips when no Vulkan device is present.
    #[test]
    fn upload_texture_paths_are_validation_clean() {
        let Some(device) = device_or_skip() else {
            return;
        };
        let before = validation_issue_count();
        let free_list: BindlessFreeList = Arc::new(Mutex::new(Vec::new()));
        let descriptors = Descriptors::new(&device, &free_list).expect("Descriptors::new");
        let queue = device.graphics_queue.clone();
        let uploader = Uploader::new(&device, &queue).expect("Uploader::new");

        // A 4×4 sRGB image: mip 0 + a blitted-down chain (mip_count(4,4) == 3).
        let rgba = vec![200u8; 4 * 4 * 4];
        let tex = uploader
            .upload_texture(&descriptors, &rgba, 4, 4, true)
            .expect("rgba8 upload");
        assert_eq!(tex.extent.width, 4);
        assert_eq!(tex.format, vk::Format::R8G8B8A8_SRGB);
        // Slot 0 is the default white; the first uploaded texture takes slot 1.
        assert_eq!(tex.bindless_index(), 1);

        // A 2×2 HDR float image → R16G16B16A16_SFLOAT, single mip.
        let hdr = vec![2.0f32; 2 * 2 * 4];
        let hdr_tex = uploader
            .upload_texture_float(&descriptors, &hdr, 2, 2)
            .expect("float upload");
        assert_eq!(hdr_tex.format, vk::Format::R16G16B16A16_SFLOAT);
        assert_eq!(hdr_tex.bindless_index(), 2);

        // A zero-sized image is rejected before any allocation.
        assert!(matches!(
            uploader.upload_texture(&descriptors, &rgba, 0, 4, false),
            Err(Error::ZeroSizedImage)
        ));

        // Dropping a texture returns its slot to the shared free-list.
        let slot = hdr_tex.bindless_index();
        drop(hdr_tex);
        assert_eq!(free_list.lock().unwrap().as_slice(), &[slot]);

        drop(tex);
        drop(uploader);
        drop(descriptors);
        device.wait_idle().expect("idle before teardown");
        drop(device);

        let after = validation_issue_count();
        assert_eq!(
            before,
            after,
            "the texture uploads must be validation-clean (saw {} new issue(s))",
            after.saturating_sub(before)
        );
    }

    /// The mip-chain length: 1×1 → 1, square powers of two → log2+1, and a non-square
    /// image uses the larger dimension.
    #[test]
    fn mip_count_spans_the_full_chain() {
        assert_eq!(mip_count(1, 1), 1);
        assert_eq!(mip_count(2, 2), 2);
        assert_eq!(mip_count(256, 256), 9);
        assert_eq!(mip_count(1024, 512), 11);
        assert_eq!(mip_count(512, 1024), 11);
        assert_eq!(mip_count(7, 1), 3); // 7 -> 3 -> 1
    }

    #[test]
    fn explicit_mip_chain_requires_every_level_exactly_once() {
        let base = vec![0_u8; 7 * 3 * 4];
        let middle = vec![0_u8; 3 * 4];
        let tail = vec![0_u8; 4];
        let valid = [
            TextureMipLevel {
                rgba: &base,
                width: 7,
                height: 3,
            },
            TextureMipLevel {
                rgba: &middle,
                width: 3,
                height: 1,
            },
            TextureMipLevel {
                rgba: &tail,
                width: 1,
                height: 1,
            },
        ];
        assert!(valid_prefiltered_mip_chain(&valid));
        assert!(!valid_prefiltered_mip_chain(&valid[..2]));

        let extra = [valid[0], valid[1], valid[2], valid[2]];
        assert!(!valid_prefiltered_mip_chain(&extra));
        let malformed = [
            valid[0],
            TextureMipLevel {
                rgba: &tail,
                width: 2,
                height: 1,
            },
            valid[2],
        ];
        assert!(!valid_prefiltered_mip_chain(&malformed));
        assert!(!valid_prefiltered_mip_chain(&[]));
    }
}
