[package]
name = "saffron-vegetation"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
saffron-core = { path = "../core" }
saffron-json = { path = "../json" }
saffron-geometry = { path = "../geometry" }
saffron-spatial = { path = "../spatial" }
glam.workspace = true
optimesh.workspace = true
sha2.workspace = true
thiserror.workspace = true
zstd.workspace = true
